import * as constants from './constants';

interface Quotes
{
    category: string;
    language: string;
    sentences: string[];
}

const quotes: Quotes[] = [
    {
        category: constants.CATEGORY_WISE_SAYING,
        language: constants.LANG_ENGLISH,
        sentences: [
            "If you want to achieve greatness stop asking for permission. - Anonymous",
            "Things work out best for those who make the best of how things work out. - John Wooden",
            "To live a creative life, we must lose our fear of being wrong. - Anonymous",
            "If you are not willing to risk the usual you will have to settle for the ordinary. - Jim Rohn",
            "Trust because you are willing to accept the risk, not because it's safe or certain. - Anonymous",
            "Take up one idea. Make that one idea your life- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
            "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
            "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
            "If you do what you always did, you will get what you always got. - Anonymous",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "Just when the caterpillar thought the world was ending, he turned into a butterfly. - Proverb",
            "Successful entrepreneurs are givers and not takers of positive energy. - Anonymous",
            "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
            "Opportunities don't happen, you create them. - Chris Grosser",
            "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
            "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
            "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
            "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it. - Kim Garst",
            "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
            "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
            "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
            "If you're going through hell keep going. - Winston Churchill",
            "The ones who are crazy enough to think they can change the world, are the ones who do. - Anonymous",
            "Don't raise your voice, improve your argument. - Anonymous",
            "What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
            "The meaning of life is to find your gift. The purpose of life is to give it away. - Anonymous",
            "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
            "When you stop chasing the wrong things, you give the right things a chance to catch you. - Lolly Daskal",
            "I believe that the only courage anybody ever needs is the courage to follow your own dreams. - Oprah Winfrey",
            "No masterpiece was ever created by a lazy artist. - Anonymous",
            "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
            "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
            "Blessed are those who can give without remembering and take without forgetting. - Anonymous",
            "Do one thing every day that scares you. - Anonymous",
            "What's the point of being alive if you don't at least try to do something remarkable. - Anonymous",
            "Life is not about finding yourself. Life is about creating yourself. - Lolly Daskal",
            "Nothing in the world is more common than unsuccessful people with talent. - Anonymous",
            "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. - Anonymous",
            "Your problem isn't the problem. Your reaction is the problem. - Anonymous",
            "You can do anything, but not everything. - Anonymous",
            "Innovation distinguishes between a leader and a follower. - Steve Jobs",
            "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
            "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. - A.P.J. Abdul Kalam",
            "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
            "The starting point of all achievement is desire. - Napoleon Hill",
            "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
            "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
            "All progress takes place outside the comfort zone. - Michael John Bobak",
            "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
            "Courage is resistance to fear, mastery of fear- not absence of fear. - Mark Twain",
            "Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
            "People often say that motivation doesn't last. Well, neither does bathing- that's why we recommend it daily. - Zig Ziglar",
            "We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "Too many of us are not living our dreams because we are living our fears. - Les Brown",
            "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. - Martha Stewart",
            "It's not what you look at that matters, it's what you see. - Anonymous",
            "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
            "The function of leadership is to produce more leaders, not more followers. - Ralph Nader",
            "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
            "As we look ahead into the next century, leaders will be those who empower others. - Bill Gates",
            "A real entrepreneur is somebody who has no safety net underneath them. - Henry Kravis",
            "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
            "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. - Tony Robbins",
            "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. - Audre Lorde",
            "Whenever you find yourself on the side of the majority, it is time to pause and reflect. - Mark Twain",
            "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
            "There is no traffic jam along the extra mile. - Roger Staubach",
            "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
            "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. - Jim Rohn",
            "If you genuinely want something, don't wait for it- teach yourself to be impatient. - Gurbaksh Chahal",
            "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
            "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! - T. Harv Eker",
            "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something- your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. - Steve Jobs",
            "Two roads diverged in a wood and I  took the one less traveled by, and that made all the difference. - Robert Frost",
            "The number one reason people fail in life is because they listen to their friends, family, and neighbors. - Napoleon Hill",
            "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them. - Denis Waitley",
            "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
            "Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
            "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
            "You must expect great things of yourself before you can do them. - Michael Jordan",
            "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
            "People rarely succeed unless they have fun in what they are doing. - Dale Carnegie",
            "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. - Ella Wheeler Wilcox",
            "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter. - Francis Chan",
            "You've got to get up every morning with determination if you're going to go to bed with satisfaction. - George Lorimer",
            "A goal is not always meant to be reached; it often serves simply as something to aim at. -  Bruce Lee",
            "Success is ... knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. - John C. Maxwell",
            "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. - Wayne Dyer",
            "To accomplish great things, we must not only act, but also dream, not only plan, but also believe. - Anatole France",
            "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all. - Dale Carnegie",
            "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. - Booker T. Washington",
            "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. - Theodore N. Vail",
            "It is better to fail in originality than to succeed in imitation. - Herman Melville",
            "What would you do if you weren't afraid. - Spencer Johnson",
            "Little minds are tamed and subdued by misfortune; but great minds rise above it. - Washington Irving",
            "Failure is the condiment that gives success its flavor. - Truman Capote",
            "Don't let what you cannot do interfere with what you can do. - John R. Wooden",
            "You may have to fight a battle more than once to win it. - Margaret Thatcher",
            "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done. - Vince Lombardi",
        ],
    },
    {
        category: constants.CATEGORY_WISE_SAYING,
        language: constants.LANG_KOREAN,
        sentences: [
            '명성을 쌓는 것에는 20년이란 세월이 걸리며 명성을 무너뜨리는 것에는 5분도 걸리지 않는다. 그걸 명심한다면 당신의 행동이 달라질 것이다. - 워렌버핏',
            '간단함이 훌륭함의 열쇠다. - 이소룡',
            '승리하면 조금 배울 수 있고, 패배하면 모든 것을 배울 수 있다. - 크리스티 메튜슨',
            '승자는 책임지는 태도로 살며, 패자는 약속을 남발한다. - 유태경전',
            '말만 하고 행동하지 않는 사람은 잡초로 가득 찬 정원과 같다. - 하우얼',
            '내 자신의 무식을 아는 것은 지식에로의 첫걸음이다. - 바이런',
            '가시에 찔리지 않고서는 장미를 모을 수 없다. - 핀페이',
            '고통을 거치지 않고 얻은 승리는 영광이 아니다. - 나폴레옹',
            '기와한장 아껴서 대들보 썩는다. - 한국속담',
            '바람이 불지 않으면 노를 저어라. - 윈스턴 처칠',
            '강에서 물고기를 보고 탐내는 것보다 돌아가서 그물을 짜는 것이 옳다. - 예악지',
            '역경은 사람을 부유하게 하지는 않으나 지혜롭게 한다. - 풀러',
            '낭비한 시간에 대한 후회는 더 큰 시간 낭비이다. - 메이슨 쿨리',
            '들은 것은 잊어버리고, 본 것은 기억하고 직접 해본 것은 이해한다. - 공자',
            '산을 움직이려 하는 이는 작은 돌을 들어내는 일로 시작한다. - 공자',
            '앞날을 결정짓고자 하면 옛것을 공부하라. - 공자',
            '아이디어의 좋고 나쁨은 어떻게 실행하느냐에 따라 결정된다. - 카를로스 곤',
            '절대 포기하지 마라. 장벽에 부딪히거든, 그것이 절실함을 나에게 물어보는 장치에 불과하다는 것을 잊지 마라. - 랜디 포시',
            '현재와 미래는 어떻게든 연결되어 있다 - 스티브 잡스',
            '모든 기능은 유지비용이 든다. 소수의 기능을 가지는 것은 우리가 정말로 신경쓰는 것에 집중하도록 하고 그것들이 뛰어나도록 만든다. - 데이비드 카프',
            '시도해보지 않고는 누구도 자신이 얼마만큼 해낼 수 있는지 알지 못한다. - 푸블릴리우스 시루스',
            '다리를 움직이지 않고는 작은 도랑도 건널 수 없다. - 알랭',
            '항상 갈구하라. 바보짓을 두려워마라. - 스티브 잡스',
            '비장의 무기는 아직 손안에 있다.그것은 희망이다. - 나폴레옹',
            '성공을 위한 세가지 열쇠는 이것이다. 첫째는 끈기, 둘째는 끈기, 셋째도 끈기. - 이소룡',
            '성공의 커다란 비결은 결코 지치지 않는 인간으로 인생을 살아가는 것이다. - 알버트 슈바이처',
            '나는 그저 나보다 머리가 좋은 사람들을 채용했을 뿐이다. - 록펠러',
            '18년동안 아마존을 성공으로 이끈 3가지 큰 전략이 있다.그것은 고객을 우선 생각하고, 발명하고, 인내하는 것이다. - 제프 베조스',
            '가끔은 혁신을 추구하다 실수할 때도 있다. 하지만 빨리 인정하고 다른 혁신을 개선해 나가는 것이 최선이다. - 스티브 잡스',
            '휴식은 게으름도, 멈춤도 아니다. - 헨리 포드',
        ],
    }
];

export default quotes;